### ISSUE TITLE
An unexpected error has occurred 

### ISSUE THREAD

**Issue by giorgix3** [DP-3T/dp3t-app-ios-ch#109]
![3266A2EC-2935-4D02-AB4E-AC72A6CF5E67](https://user-images.githubusercontent.com/6891142/84469566-a3f93b80-ac81-11ea-9deb-bba2d07859a8.png)

![765BB584-A880-4EB6-956D-272F674C7C2C](https://user-images.githubusercontent.com/6891142/84469633-d440da00-ac81-11ea-8ef5-39ff25aa3314.png)

My App (App Store, v 1.0.2, iOS 13.5, iPhone 11 Pro) regularly shows these messages. Closing and reopening the app temporarily solves the issue.

**Comment by thebluepotato** [comment]
I've updated from the TestFlight to the AppStore version just now and I also have ENErrorCodeBadParameter (realpath failed). (I'm an employee of the University of Lausanne).

**Comment by stmitt** [comment]
This issue has been resolved with the newest SDK version. Thanks for your feedback!
