### ISSUE TITLE
Excessive exposure checks?

### ISSUE THREAD

**Issue by gabac** [DP-3T/dp3t-app-ios-ch#119]
While checking the exposure checks logs I noticed that there are more than expected checks.

I seems to be correlated to the `Provided Key Count`. I have 10 `Provided Key Count` and 10 logs.
Is this expected?

App version: `200613.4.142p`

![IMG_7937](https://user-images.githubusercontent.com/50061/84634135-acf04400-aef1-11ea-9a03-32675ed2523e.png)
![IMG_7938](https://user-images.githubusercontent.com/50061/84634141-b11c6180-aef1-11ea-9335-38116789969a.jpeg)

**Comment by martinsteiger** [comment]
It's part of the testing: https://twitter.com/waellig/status/1270803576693174273

**Comment by gabac** [comment]
Also with this explanation it now make sense!

https://github.com/DP-3T/dp3t-sdk-ios/blob/master/EXPOSURE_NOTIFICATION_API_USAGE.md#rate-limit
