### ISSUE TITLE
App doesn't recreate bluetooth managers when relaunched

### ISSUE THREAD

**Issue by gamagros** [DP-3T/dp3t-app-ios-ch#140]
When app is relaunched by the system because of any change in bluetooth managers, the app doesn't reinitiate the managers because the function shouldSetupWindow returns false when in background.

A possible solution is to move the call TracingManager.shared.beginUpdatesAndTracing() to didFinishLaunching. That is, remove it from setupWindow() and writing this in didFinish... :

// defer window initialization if app was launched in
        // background because of location change
        if shouldSetupWindow(application: application, launchOptions: launchOptions) {
            setupWindow()
            TracingManager.shared.beginUpdatesAndTracing()
            willAppearAfterColdstart(application, coldStart: true, backgroundTime: 0)
        } else if let identifiers = launchOptions?[.bluetoothCentrals] as? [String],
            identifiers.count > 0 {
            TracingManager.shared.beginUpdatesAndTracing()
        }

**Comment by stmitt** [comment]
The implementation does not use CoreBluetooth anymore, we use the Exposure Notification framework. Therefore there is no need for this change.
