### ISSUE TITLE
IEN11 and Insufficient Memory popup

### ISSUE THREAD

**Issue by stmitt** [DP-3T/dp3t-app-ios-ch#162]
On iOS 13.5 the Error [IEN11](https://developer.apple.com/documentation/exposurenotification/enerror/code/internal) was observed on some devices. In addition to that we got an insufficient memory popup on that device even though there is plenty of space available. 
 ![popup](https://user-images.githubusercontent.com/1466567/85549486-5802ab00-b620-11ea-84f1-e7677d38f7ba.png)

According to Apple this Issue will be resolved with the release of iOS 13.6.

**Comment by kferrari** [comment]
Same here with iOS 13.5.1 on iPhone 11 with SwissCovid v1.0.5

After the pop-up, SwissCovid showed an unexpected error. Both seem to have vanished after a reboot of the device.

**Comment by esosan** [comment]
Same here with iOS 13.5.1 on iPhone 7 with SwissCovid 1.0.6.

Is the App still saving the new contacts? 

<img width="375" alt="Istantanea schermo 2020-07-14 (08 18 52)" src="https://user-images.githubusercontent.com/11174817/87391402-f3959480-c5aa-11ea-91c6-06be08b356c3.png">

**Comment by UBaggeler** [comment]
This is an error of iOS and will be fixed in the next version of iOS (13.6). iOS 13.6 beta is already available if you want to update.

**Comment by esosan** [comment]
Thank you. So new contacts are still saved?

**Comment by UBaggeler** [comment]
We could never reproduce this error consistently, to be able to investiage whether IDs are are still being exchanged. Please update to iOS 13.6, which was released by Apple a few hours ago.
