### ISSUE TITLE
ENErrorDomain-Fehler 5

### ISSUE THREAD

**Issue by HenrikMettler** [DP-3T/dp3t-app-ios-ch#166]
Panel 'Meldungen' shows: 
_Ein unerwarteter Fehler ist aufgetreten. 
Der Vorgang konnte nicht abgeschlossen werden (ENErrorDomain-Fehler 5.)_

-iPhone SE 2020, iOS 13.5.1
-no previous installation of tracking apps of other countries

(Some users of the german app seem to have a similar issue: [https://github.com/corona-warn-app/cwa-app-ios/issues/766](url)

**Comment by benoitpointet** [comment]
Same w mine:
* iOS 13.5.1
* iPhone 6s Plus

**Comment by FabBaur** [comment]
Same issue here

* iOS 13.5.1
* iPhone 11

**Comment by miloscekovic** [comment]
Same issue for:

- iPhone 11 Pro
- iOS 13.5.1

**Comment by ClaudiaHof** [comment]
Same issue here

iOS 13.5.1
iPhone X

Delete, reboot iPhone and reinstall does not solve the issue.

**Comment by ronxorange** [comment]
Same here... IOS13.5.1 Iphone XI. 
Just for information: I used the German App Store.

**Comment by FabBaur** [comment]
Bei mir ist der Fehler eben verschwunden. Ich hatte Kontakt zu einem Arbeitskollegen mit einem iPhone und seither habe ich Einträge im Kontaktprotokoll und der Fehler wird in der App nicht mehr angezeigt.

**Comment by jp-io** [comment]
Same here for: iOS 13.5.1, iPhone SE (1st generation, Mo.#:NLM62DN/A).
No previous installs, installed ca 1.5h ago. I use the swiss app store and have my phone set to English.
![IMG_3066AF1A29ED-1](https://user-images.githubusercontent.com/7782260/85918979-bb324e80-b867-11ea-8f71-76d49fcf3bea.jpeg)

**Comment by UBaggeler** [comment]
Is anyone with this error willing to update to iOS 13.6 beta 2 (https://betaprofiles.com/ios13)? If anyone is able to reproduce this on iOS 13.6 beta 2 we can forward a sysdiagnose to Apple to analyse this further.

**Comment by miloscekovic** [comment]
I reported this issue 5 days ago. It occurs on my:
- iPhone 11 Pro
- iOS 13.5.1
The phone standard language is english. 

I set the prefered language for the SwissCovid app to german. The error disappeared. Maybe this is a coincidence. If I switch back to englixh, the rror is still not here. So I cannot reproduce this behaviour, but the error disappeared for me.

**Comment by ClaudiaHof** [comment]
The error disappeared - probably for the same reason as in case of FabBaur: I had contact with approx. 8 other users who have installed the app.

**Comment by jp-io** [comment]
The error has disappeared for me as well, no changes were made.
