### ISSUE TITLE
Tracing deactivates after iOS Uodat

### ISSUE THREAD

**Issue by nuggie2** [DP-3T/dp3t-app-ios-ch#168]

**Comment by nuggie2** [comment]
After updating to iOS 14.0. (beta), tracing is deactivated.
In Settings, privacy, health, tracing cannot be activated. Message is : tracing not available in your region. On XSmax, Region Basel, network provider Salt. Prior to update, tracing was working as expected.
![1ED6DFED-21CC-4ADA-A470-0E983648A71C](https://user-images.githubusercontent.com/67467570/85856826-017ca480-b7b9-11ea-847d-fd90416a3881.png)
![A784683B-D44D-4E75-8F5A-B265ED3EDD3D](https://user-images.githubusercontent.com/67467570/85856844-06d9ef00-b7b9-11ea-9414-ff3240249e34.png)

**Comment by stmitt** [comment]
This is a known Issue.
https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes#ExposureNotification
