### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by n0rdlicht** [DP-3T/dp3t-app-ios-ch#169]
One difference from running both the German Corona Warn and SwissCovid App I noticed the currently missing dark mode in SwissCovid. Is this in the Roadmap or considered out of scope? Design wise MeteoSwiss recently implemented a dark mode with a similar design language as SwissCovid.

**Comment by joseph-elmallah** [comment]
@alexandru-lazar This would be the open Issue for dark mode support. For any further discussions during your implementation, please update this thread. Once you have a pull request ready, please don't forget to link it to the issue.

**Comment by alexandru-lazar** [comment]
Pull request regarding Dark mode. https://github.com/DP-3T/dp3t-app-ios-ch/pull/196

**Comment by UBaggeler** [comment]
This was released in 1.0.9 which is currently being rolled out (phased).

@alexandru-lazar thanks for your contribution!
