### ISSUE TITLE
Proximity tracing is not activated

### ISSUE THREAD

**Issue by LKS90** [DP-3T/dp3t-app-ios-ch#171]
Hi there!

Basically a repeat of this issue: https://github.com/DP-3T/dp3t-app-ios-ch/issues/69

I have a phyiscal Swisscom SIM-card, removing (not offloading) the app and trying to fiddle around with any settings brings no luck. The toggle inside the app about activating proximity tracing does nothing. During the setup, there is the step about activating poximity tracing and from the issue above, it reads like this would redirect me to some setting, but this doesn't happen either. When I click activate it just jumps to the next step (Report of potential infection). "Enable messages" after that does bring up the dialog about giving SwissCovid permissions for notifications.

Now I am at the same end result as the previous two tries: No proximity tracing. Settings -> Privacy -> Health shows the COVID-19 Exposure logging to be turned off, it says it is not available in my region. Same with Settings -> Privacy -> Bluetooth.

**Comment by LKS90** [comment]
I have of course tried the workarounds mentioned in the other issue, without success.

**Comment by UBaggeler** [comment]
Which version of iOS is installed on your iPhone? Can you try to reproduce this on iOS 13.6 beta 2 (https://betaprofiles.com/ios13)?

**Comment by LKS90** [comment]
I had the latest stable release installed before that (iOS 13.5.1), I have now tried the same procedure with iOS 13.6 beta 2 and have not gotten any positive results. I had a lot of privacy options disabled, one of them was sharing data with app developers. I have enables this now (and a couple of other options, except Beta reporting, Siri improvement and iCloud related settings), but still no dice. Maybe the sharing data with app developers helps you at all?

**Comment by LKS90** [comment]
Issue fixed for me after updating to a beta release, activating monitoring profiles and knocking at Apple's door.
