### ISSUE TITLE
Permanent Unexpected Error - ENErrorDomain 5

### ISSUE THREAD

**Issue by iomaz** [DP-3T/dp3t-app-ios-ch#176]
I have this error showing permanently

App V 1.0.5
On  iPhone 6s  IOS V13.5.1

![SwissCovid Error](https://user-images.githubusercontent.com/20907033/86181857-177ac400-bb2f-11ea-8348-b1e97e96c254.PNG)
![Iphone Info](https://user-images.githubusercontent.com/20907033/86181864-19dd1e00-bb2f-11ea-9938-6d5ef3db267d.PNG)

**Comment by UBaggeler** [comment]
This is an error of Apple's Exposure Notification framework. Can you send a screenshot of iOS Settings > Privacy > Health > COVID-19 Exposure Logging? If you are willing to update to iOS 13.6 beta we could help you acquire a sysdiagnose, which we can then send to Apple's engineering team.

**Comment by iomaz** [comment]
The COVID exposure log is empty

Does tracking that issue down really require me installing a ios beta version ?

Do you think you could not reproduce it with the given information ?
I would expect that configuration to be relatively common (iPhone 6s, IOS 13.5.1)

**Comment by UBaggeler** [comment]
We cannot reproduce it with the same phone and iOS version and it also works for other users with the same configuration. Unfortunately this means we can only send more details to Apple if someone, who has the error, is willing to install the update, logging profiles and trigger a sysdiagnose.

**Comment by iomaz** [comment]
The thing is that issue does not concern my own device but a relative's one.
What is the effort to install a beta version ?  and what's the risk ?  (talking about IOS 13.6 Beta 3 ?)
If the effort/risk is reasonable and you think it's helpful I'm ready to convince my wife :)

**Comment by UBaggeler** [comment]
Do you still see ENError 5? Installing the beta is not much of an effort (installing a profile and after a restart you will see a system update in the iOS settings app). This update is not much of a risk as it mainly is a bugfix release (compared to iOS 14 beta).

**Comment by iomaz** [comment]
The error has gone with the update to the SwissCovid app V1.0.6
Hope this will give you a clue on the root cause if you still look for it.

**Comment by mosea3** [comment]
For a while, there was no update available. 
After a reboot i got to download v 1.0.6. 


I guess it solves that. 
Would reopen if issue persists. 

Thankies.
