### ISSUE TITLE
Use SFSafariViewController to open links

### ISSUE THREAD

**Issue by clivazpat** [DP-3T/dp3t-app-ios-ch#180]
I have noticed that the application systematically opens links in Safari and exits the application (e.g. for frequently asked questions, protection measures, self-assessment).

Why not use [SFSafariViewController](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller) so that these links are opened natively while remaining in the application and allow a simple and quick consultation?

**Comment by UBaggeler** [comment]
If I remember correctly this was done because of legal reasons. Like this, the websites which are opened cannot be considered part of the app (which could have implications otherwise).
