### ISSUE TITLE
Region for SwissCovid App not supported

### ISSUE THREAD

**Issue by mosea3** [DP-3T/dp3t-app-ios-ch#186]
I get notifications about SwissCovid App not supporting this region for Exposure Notification, exactly like when I once left Switzerland a few weeks ago. 

Im currently in Burgdorf, Berne (way not border region). Current IP Address was: 178.197.237.88 over LTE Network Swisscom 41.0. 

Technical support of mobile operator said I wasnt roaming to another foreign network. 

![926BDE6C-4D24-4585-9F52-312AC2DB813E](https://user-images.githubusercontent.com/26161943/87073234-5a1e5980-c21d-11ea-867d-5941a88dab59.png)

**Comment by UBaggeler** [comment]
This is a bug in iOS 13.5.x. According to Apple this issue should be fixed in the next version of iOS (13.6 beta currently available).

**Comment by UBaggeler** [comment]
iOS 13.6 was released today. Please reopen if you get this notification again.
