### ISSUE TITLE
App is not fully compatible with iOS 14

### ISSUE THREAD

**Issue by Desmo46** [DP-3T/dp3t-app-ios-ch#187]
The app installs correctly on iOS 14 however it is not activating the tracing functionality.

Using iOS 14 Beta 2 which reintroduced the contract tracing functionality.
![F8AABC9B-3FBE-40BE-8636-AAED7692D265](https://user-images.githubusercontent.com/8146306/87096538-5c93aa00-c243-11ea-9437-5f7ff394ac9a.png)
![E0977B18-9ACF-4EEC-9C8A-E7564A2B9AA9](https://user-images.githubusercontent.com/8146306/87096545-60273100-c243-11ea-9db8-9b23751b2067.png)

**Comment by UBaggeler** [comment]
Apple notes in the release notes of iOS 14 beta 2 (https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes) that EN is not available:

- ExposureNotification isn’t currently available in iOS 14 beta. Use iOS 13.6 beta to preview the latest functionality. (64433241)

**Comment by Desmo46** [comment]
Apologies I completely misread it.  Closing the issue.
