### ISSUE TITLE
Changes between 1.05 and 1.06

### ISSUE THREAD

**Issue by r-r-liu** [DP-3T/dp3t-app-ios-ch#202]
I just noticed the update to 1.06 in the iOS App Store.  The Version History doesn't reveal what changes were made between 1.05 and 1.06.  Are they available somewhere?  Thanks.

**Comment by 7thsonch** [comment]
https://github.com/DP-3T/dp3t-app-ios-ch/releases

**Comment by r-r-liu** [comment]
Sorry, I didn't see that.  Thanks.
