### ISSUE TITLE
Need to restart app or reboot iPhone after update?

### ISSUE THREAD

**Issue by r-r-liu** [DP-3T/dp3t-app-ios-ch#205]
I updated the app from the iOS App Store on July 14 and, seemingly, the app only pulled exposures from the backend once since July 14, early on July 15.  Suspicious, I restarted the iPhone, and the app immediately pulled exposures.  Does the app need to be restarted, or the iPhone rebooted, after the update.  Of course, it was running even during the update.

**Comment by UBaggeler** [comment]
Apple fixed several issues in background tasks scheduling in iOS 13.6. Additionally we've als made some improvements in the upcoming SwissCovid update (1.0.7). Can you try to update to iOS 13.6 and verify whether you still observe this issue?

**Comment by r-r-liu** [comment]
OK, I’ve just seen 13.6.  I’ll upgrade at the latest tonight.  Yesterday, after upgrading to app version 1.06 without restarting either app or iPhone I see one bunch of exposures at about 1 am, none thereafter.  Today after restarting the iPhone, I received another bunch.  Prior to the update I had been receiving two a day at different times.  Should it still be two in 1.06, or has that changed?

**Comment by r-r-liu** [comment]
I installed iOS 13.6 yesterday afternoon around 14:00.  By then the app had fetched exposure records once at about 9:00.  That same evening around 19:00 it fetched again.  And this morning around 9:00 I see another fetch.  I am assuming it should be fetching twice a day and things are back to normal.  I it performs another fetch tomorrow I will close this ticket.

**Comment by r-r-liu** [comment]
There was another fetch this evening at around 19:00.  That makes two for today.  Seems everything is back to the way it was under iOS 13.5.1 and 1.05, so I'm closing this issue.  Thanks.
