### ISSUE TITLE
iOS 13.6: Misleading German translation of "Weekly Update" notification

### ISSUE THREAD

**Issue by UBaggeler** [DP-3T/dp3t-app-ios-ch#228]
Starting with iOS 13.6, Apple decided to show a weekly notification to the user: 

> Your device identified 0 potential exposures this week, and shared them with SwissCovid. 

To German this was translated to: 

> Dein Gerät hat diese Woche 0 mögliche Begegnungen identifiziert und diese Info mit SwissCovid geteilt. 

This is misleading, as it does not say "[...] 0 **positiv getestete** Begegnungen [...]". Without this distinction, it might be understood that the app does not work at all, even though SwissCovid and Exposure Notifications are working as intended. 

![Unknown](https://user-images.githubusercontent.com/35527968/88086384-95a71500-cb87-11ea-922a-bbc479244cea.png)

This issue was reported to Apple.

**Comment by 7thsonch** [comment]
I have a question which at least indirectly relates to this issue.
iOS today showed me "Your device identified 2 potential exposures this week" in its weekly push message. The SwissCovid app has not reported anything yet.
I assume Apple's exposure framework recorded 2 encounters with infected people, but the app then independently determines whether there is really a possible infection (because contact longer than ~15 minutes and distance less than about 2 meters etc.), right?

If so, it might be useful to put a note in the FAQs if people feel unsettled by such push messages from Apple.

**Comment by UBaggeler** [comment]
> I have a question which at least indirectly relates to this issue.
> iOS today showed me "Your device identified 2 potential exposures this week" in its weekly push message. The SwissCovid app has not reported anything yet.
> I assume Apple's exposure framework recorded 2 encounters with infected people, but the app then independently determines whether there is really a possible infection (because contact longer than ~15 minutes and distance less than about 2 meters etc.), right?

Have you checked inside the app, whether you received a message? Indeed, Apple shows "potential exposures" in the notification as soon as a match was identified, independent of the app's calculation whether this exposure was long or close enough. So it can happen, that you get this message from Apple but no notification from SwissCovid.
 
> If so, it might be useful to put a note in the FAQs if people feel unsettled by such push messages from Apple.

I agree. Will forward this feedback.

**Comment by 7thsonch** [comment]
> Have you checked inside the app, whether you received a message?
Yes I have - no message inside the app. Lucky me :-)

**Comment by clivazpat** [comment]
What about the French translation? Isn't that the same problem?
![B7143DCC-E2C9-49C8-A47D-57360C68D7B3](https://user-images.githubusercontent.com/25901612/88905103-37002c00-d256-11ea-83ef-6eeb13612ea2.jpeg)

**Comment by pdehaye** [comment]
Is this already in production on iOS 13.6? 

This could happen ([it seems](https://twitter.com/GranjonArabeske/status/1291007530748043264?s=20)) also when there _are_ potential exposures (at least to GAEN's judgment), but SwissCovid decides not to notify. 

This would very quickly undermine any trust in the app and create massive complications in terms of customer support. You should probably be all-hands-on-deck trying to fix this.

**Comment by chrigi** [comment]
I also got the message about "8 potential exposures" but the app shows "No Reports". I think this situation is very confusing. I would expect the Report Detail Screen to at least acknowledge these matches and explain why they have not triggered a notification. Hiding it in an FAQ doesn't improve this much.

**Comment by stmitt** [comment]
We are addressing this issue in our [FAQ](https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/faq-kontakte-downloads/haeufig-gestellte-fragen.html?faq-url=/en/swisscovid-app-technology/what-are-weekly-reminder-messages-android-and-ios) and are in contact with Apple to resolve this in upcoming iOS releases.

**Comment by rachyandco** [comment]
@stmitt It seems this issue is still open and the FAQ change was not enough to mitigate it. 

See https://twitter.com/fredalvar/status/1294190183341068293 it seems that the help line has a high number of calls related to this.

**Comment by pdehaye** [comment]
This is still causing confusion, for instance here: https://twitter.com/andybiotika3/status/1298154133686554624

**Comment by UBaggeler** [comment]
I agree this is confusing and we repeatedly told Apple. We are working towards explaining this issue in the app.

**Comment by pdehaye** [comment]
Still:
* https://twitter.com/dagmarhuebscher/status/1299618832089317376?s=20

**Comment by pdehaye** [comment]
Still:
* https://twitter.com/dagmarhuebscher/status/1299618832089317376?s=20
* https://twitter.com/andybiotika3/status/1298154133686554624?s=20
* https://twitter.com/andyorange/status/1299639721543585792?s=21
* https://twitter.com/ooswald/status/1300086437837242369?s=21

**Comment by UBaggeler** [comment]
It seems things are starting to move in this regard. Apple is changing it from a weekly notification to a monthly notification in the upcoming release of iOS 13.7 (currently available as beta to developers). Also, the notification won't include any numbers (matches) anymore but inform users in general, that the iPhone continues to look for possible exposures.

**Comment by pdehaye** [comment]
* https://twitter.com/yagmur_erten/status/1301845370750803969?s=20
* https://twitter.com/ferdinandvogler/status/1303923196832501764

**Comment by pdehaye** [comment]
https://www.rts.ch/info/sciences-tech/11587953-des-alertes-trompeuses-sur-le-covid-inquietent-les-utilisateurs-diphone.html

**Comment by pdehaye** [comment]
For completeness, I asked the BAG/FOPH/OFSP for their analytics data on the FAQ page discussing the iOS issue. 

<img width="821" alt="Screenshot 2020-09-18 at 09 40 41" src="https://user-images.githubusercontent.com/3274335/93571341-9a742380-f994-11ea-83fd-6c52e2390454.png">
<img width="667" alt="Screenshot 2020-09-18 at 09 40 55" src="https://user-images.githubusercontent.com/3274335/93571350-9cd67d80-f994-11ea-895e-5b8cc1e171df.png">
