### ISSUE TITLE
error message "Zu wenig Speicher, um COVID-19-..."

### ISSUE THREAD

**Issue by McSvenster** [DP-3T/dp3t-app-ios-ch#229]
Though I still have over 20GB left on my device the app says:Zu wenig Speicher, um COVID-19-Kontaktmitteilungen zur Verfügung zu stellen" ... "Um diese IDs zu sichern, benötigt dein iPhone mehr Speicher."...

This happens irregularly - I suspect it has something to do when the iPhone books into a foreign network (Germany, Liechtenstein, Austria...)

![IMG_2476](https://user-images.githubusercontent.com/147500/88188341-0279e800-cc38-11ea-95f1-fc82df2736c9.jpeg)

**Comment by UBaggeler** [comment]
Tritt das Problem unter iOS 13.6 auch noch auf? Sollte laut Apple nicht mehr vorkommen.

**Comment by McSvenster** [comment]
OMG, tut mir leid! Ich habe nicht bemerkt, dass sich mein iPhone noch nicjht auf 13.6 aktualisiert hat. Werde es testen und im Fall neu melden.
