### ISSUE TITLE
Neuer Hinweis auf Startscreen ist nicht mit VoiceOver erreichbar 

### ISSUE THREAD

**Issue by aigsler** [DP-3T/dp3t-app-ios-ch#246]
Betrifft Barrierefreiheit.

Der neue Hinweis auf dem Startscreen wird von VoiceOver nicht vorgelesen und der Link ist über VoiceOver nicht erreichbar.

Die einzige Info die VoiceOver bei Fokus auf den Hinweis ausgibt ist: "Möglicherweise, Information".

![Hinweis auf Startscreen](https://user-images.githubusercontent.com/68910987/88675205-fcc64b80-d0ea-11ea-918b-c9cd65ec5604.PNG)

**Comment by stmitt** [comment]
Vielen Dank für Ihr Feedback. Dieser Bug wurde mit Pull Request https://github.com/DP-3T/dp3t-app-ios-ch/pull/238 resolved und wurde mit release 1.0.8 released. https://github.com/DP-3T/dp3t-app-ios-ch/releases/tag/1.0.8-200728.1245.356

**Comment by aigsler** [comment]
Danke für die Info, ich habe mir gleich die Version 1.0.8 angeschaut. Der Hinweis wird nun vorgelesen, die Taste "Weitere Informationen" ist allerdings immer noch nicht mit VoiceOver erreichbar.
