### ISSUE TITLE
Failing fake request

### ISSUE THREAD

**Issue by ineiti** [DP-3T/dp3t-app-ios-ch#265]
What happens if the fake requests fails here

https://github.com/DP-3T/dp3t-app-ios-ch/blob/7416258b4ecdbe2650ebf8ff85652fe22cc5cc7e/DP3TApp/Logic/Tracing/Reporting/FakePublishManager.swift#L112
?

It seems like it will not reschedule a new request - is that correct?

**Comment by UBaggeler** [comment]
This means the `nextScheduledFakeRequestDate` will not be modified and will still be in the past. The next time the background task is started (in 2h), it will therefore try again. And again,...
