### ISSUE TITLE
Push message stating possible infection yet when accessing app, no reports

### ISSUE THREAD

**Issue by dianavonballmoos** [DP-3T/dp3t-app-ios-ch#288]
iPhone 11 pro and iPhone 7 
iOS 13.6.1
SwissCovid app version 1.0.8

This morning I received a push notification that I have been 'possibly exposed' to someone
When I go into the app, there are no reports. I could not get a screenshot because as soon as I went into the app, the message disappeared. 
My coworker got the same message but on Sunday afternoon.

**BUG**
We receive a push notification stating possible exposure
When we go into the SwissCovid app, there are NO REPORTS (No potential infections have been reported)

**EXPECTED**
Only receive a push notification if there is a report of infection otherwise it's confusing and we are not sure what to do with that message?

![CovidAppBug](https://user-images.githubusercontent.com/65663583/91812986-3df1d400-ec32-11ea-9e15-75039744fb21.png)

Contact info for me is dianavonballmoos@hotmail.com or 076.578.34.19 if you have any questions.

**Comment by UBaggeler** [comment]
Is it possible that you got the following notification (with 1 or more potential exposure)?
![IMG_8935](https://user-images.githubusercontent.com/35527968/91813747-70e89780-ec33-11ea-90f9-cc6eccf42ba9.jpg)

This notification is generated by iOS (Apple) and not by the SwissCovid app. This was Apple's attempt to increase transparency for the user. It only shows whether your device collected an ID from someone who later testet positive, but does not respect the time or distance estimation which SwissCovid uses. As long as there is no notification of the SwissCovid app itself and a positive report inside the app, you can ignore the notification.

Also discussed in #228.

**Comment by dianavonballmoos** [comment]
Thank you for your fast response! We think this is it and my colleague's message said '24' and mine said '1' which is why we were confused. Apple should not be doing this but I'm sure you already agree :). Thanks again!

**Comment by UBaggeler** [comment]
Indeed, I find this very confusing and we told Apple repeatedly. As already mentioned in #228, it seems they finally understand the problem and are trying to improve this. I am not sure whether this solves the problem completely but it is definitely less confusing than now.

**Comment by dianavonballmoos** [comment]
I'll go ahead and close this since it's already being addressed, cheers to your fast response!
