### ISSUE TITLE
No comparison of contacts

### ISSUE THREAD

**Issue by dhartmann84** [DP-3T/dp3t-app-ios-ch#295]
For some time now, no contact data have been matched on my phone.  Has anyone else got the error?

![33EEF62C-B83B-40AB-8E26-9775720E6E2E](https://user-images.githubusercontent.com/53118468/92647193-c550de80-f2e7-11ea-925f-7b29dcff20eb.jpeg)

iOS 13.7 / Appversion 1.0.9

**Comment by UBaggeler** [comment]
Apple changed this view in iOS 13.7. It now only shows matches with people who tested positive ("Abgeglichene Schlüssel"). When you tap on the respective file (below) you will get more details like in previous iOS versions ("Bereitgestellte Schlüssel").

**Comment by dhartmann84** [comment]
Thanks for the answer, so everything is perfect.
