### ISSUE TITLE
flightmode deactivate

### ISSUE THREAD

**Issue by dhartmann84** [DP-3T/dp3t-app-ios-ch#296]
I always put my phone on airplane mode at night.  If I deactivate flight mode in the morning, the following information appears since 1.0.9.

![01CE6843-8B86-4F11-9874-3F12D8B8EAC1](https://user-images.githubusercontent.com/53118468/92863824-b27bfe00-f3fc-11ea-8cda-447b6ba148d0.jpeg)

Thank you.

**Comment by UBaggeler** [comment]
This should not happen. Unfortunately we were unable to reproduce this issue. If you're willing to help out with a sysdiagnose (collecting log files) please contact me (aggeler@ubique.ch).

**Comment by tschibi** [comment]
I noticed the same effect this morning. Iphone over the night in airplane mode, deactivated in the morning airplane mode, then also received this notification.
iPhone Xs Fw13.7 App1.0.9

**Comment by UBaggeler** [comment]
This should not happen anymore. If you are still experiencing this, please let us know.

**Comment by dhartmann84** [comment]
That problem seems to have been solved, I'll close the issue.
