### ISSUE TITLE
Question from IOS when entering the key

### ISSUE THREAD

**Issue by glacierphoto** [DP-3T/dp3t-app-ios-ch#303]
When entering the key to report a positive test one gets an additional question from the IOS to confirm the release of information. Although the IOS language was set to German, the question is in English and may discourage the average user.

Operating system version: IOS 13.7

**Comment by UBaggeler** [comment]
This is not supposed to happen. Can you share a screenshot of your iOS "Language & Region" setting? Do you have "Deutsch (Schweiz)" set as your iPhone language?

**Comment by glacierphoto** [comment]
I can confirm that the language is set to German: 
![IMG_0957](https://user-images.githubusercontent.com/22278476/93780815-e7702800-fc28-11ea-9742-11ce3cb69fe6.PNG)

**Comment by UBaggeler** [comment]
Thanks for sharing! We were able to reproduce this with iOS 13.7 and iOS 14. We're reporting this back to Apple (as this dialog is shown by iOS and not SwissCovid).

**Comment by UBaggeler** [comment]
FB8738645

**Comment by UBaggeler** [comment]
We re-tested this issue in iOS 14.2 beta 3 and it seems to be fixed.
