### ISSUE TITLE
Request for Information:  Support for older iPhone

### ISSUE THREAD

**Issue by r-r-liu** [DP-3T/dp3t-app-ios-ch#380]
Not an issue, just a request for information concerning the support of older iPhones.

When the GAEN API was first released, I understood that it needs Blue Tooth Low Energy, which iPhones older than the 6S did not offer.  Now, it seems, some older iPhones will be able to run SwissCovid thanks to Apple's release of iOS 12.5.  Do the models impacted by this change have BTLE?  If not, how will the necessity for it be circumvented in those models?

**Comment by UBaggeler** [comment]
As I do not work for Apple, I can only describe my outside perspective. Bluetooth Low Energy (BLE) was first released in iOS 5 (2011) and therefor ready available on iOS 12. Apple first added GAEN to their latest version of CoreBluetooth/bluetoothd on iOS 13. They then had to back-port all these changes to the older version these components, find other ways for APIs which did not yet exist on iOS 12 (e.g. BackgroundProcessingTasks), as well as security fixes which were introduced in the meantime on iOS 13. In the end, ExposureNotifications on iOS 12.5 are now running the same protocol on top of BLE as the newer devices.

**Comment by r-r-liu** [comment]
OK, thanks for the information, Fabian.  That clears up a muddle I had in my head.  I had always thought that the iPhone 6S was the first model with BTLE.

______________________
Richard R. Liu
richard.liu@pueo-owl.ch
