### ISSUE TITLE
Feature Request: Covid-19 vaccination application

### ISSUE THREAD

**Issue by ralphbolliger** [DP-3T/dp3t-app-ios-ch#381]
Wouln't it be a nice extension of the SwissCovid App to offer a way within the app that the user can indicate interest of getting a Covid-19 vaccination? Of course stored centralized and secure the BAG system.

Then if my age band is requested, all the registered users will be informed through the SwissCovid App by push notification.

**Comment by UBaggeler** [comment]
Thanks for reaching out. As far as I'm aware, there is currently no plan by BAG to implement such a feature. Feel free to directly get in touch with them.
