### ISSUE TITLE
Possible Exposure

### ISSUE THREAD

**Issue by MauroSwiss88** [DP-3T/dp3t-app-ios-ch#382]
Hi, 
I have a question about the exposures. On my iOS (14.3) log, I can see a matching key from SwissCovid on every daily sinchronization since the 25th December, but I’ve  received a warning notification from the app itself. Means that, I had contact with someone who was tested positive, but I had less than 15 minutes contact with him and/or at a distance of more than 1,5 meters? Thank you in advance for your help.

**Comment by UBaggeler** [comment]
Yes, that's correct.

**Comment by MauroSwiss88** [comment]
Hi! So, if I’ve understood well, for SwissCovid there is no risk that I could be infected with that matching code I see in my log, right? Thanks for your efforts and answer.

**Comment by UBaggeler** [comment]
It means, that according to the Bluetooth signals received, you were not long enough or close enough to that person which later tested positive, for SwissCovid to show a warning. SwissCovid only shows a warning once the calculated score is above a certain threshold. Details about this calculation and the precision/recall curve can be found [here](https://github.com/admin-ch/PT-System-Documents/blob/master/SwissCovid-ExposureScore.pdf).

**Comment by MauroSwiss88** [comment]
Thank yo so much for your help! :)
