### ISSUE TITLE
Error IUNXN-999 iOS 12.5.1

### ISSUE THREAD

**Issue by marcoz2403** [DP-3T/dp3t-app-ios-ch#386]
Since Update 12.5.1 on iphone 6 got problems with the swisscovid app. No synchronisation anymore.

- "Hintergrundaktualisierung" is on
- Mobile data for the app is also on
- covid app in same wlan with Iphone x works fine
- also no synchronisation in mobile network

- Restart of iphone - not better
- new installation of app - not better
- "Begegnungsmitteilungen" deleted - not better
- tracking switched off and again on - not better

Any advice?
Thanks Marco

![image](https://user-images.githubusercontent.com/74156457/104956089-b41d8a00-59cb-11eb-8881-b14c68869cf9.jpeg)

![image](https://user-images.githubusercontent.com/74156457/104956099-b8e23e00-59cb-11eb-9c1f-c56c99c1ab8d.jpeg)

**Comment by UBaggeler** [comment]
Swisscovid 1.3.1 was released a few minutes ago. Please update to the newest app version, which fixes the issue with QuoVadis' revoked intermediate certificate (ICA).

**Comment by marcoz2403** [comment]
Dear UBaggeler
Thank you very much, with new release of SwissCovid the problem is solved.
Thanks and Regards
Marco
