### ISSUE TITLE
“Keine aktuellen Daten” (Check Internet Connection)

### ISSUE THREAD

**Issue by getflourish** [DP-3T/dp3t-app-ios-ch#389]
For a while now I see this alert. The message in a previous version was about VPN (not using any) or insecure Wifi (nope, also happens on 4G). How to fix this?

![image](https://user-images.githubusercontent.com/183989/105135130-cdb7f200-5aef-11eb-8beb-4d537847311e.png)

**Comment by stmitt** [comment]
Which app version are you using? This could be related to the revoked QuoVadis' intermediate certificate (ICA). 
Swisscovid [1.3.1](https://github.com/DP-3T/dp3t-app-ios-ch/releases/tag/1.3.1-210119.706.391) was released yesterday, can you check if the new version fixes the issue for you.

**Comment by getflourish** [comment]
After the update it still didn't work. I deleted the app and reinstalled. Now the alert is gone. 

I had the app installed for a while, not sure since when the alert was showing, but it was probably a for a week. 

The error code was 99 for the old version, then 1200 for the updated version today. 

Unfortunately I don't have more info how to reproduce. 

Fixed for me, but all I can say is that the update alone didn't work, had to reinstall.

**Comment by stmitt** [comment]
Thank you for the feedback @getflourish. Can you please contact me directly at mitterrutzner(at)ubique.ch so I can provide you with a test version of Swisscovid which helps us to find the issue.

**Comment by UBaggeler** [comment]
@getflourish Thanks for your help. Swisscovid 1.3.2 is now available in the AppStore.

**Comment by getflourish** [comment]
Awesome, just updated and the issue seems to be fixed!
