### ISSUE TITLE
Testflight build?

### ISSUE THREAD

**Issue by vistalba** [DP-3T/dp3t-app-ios-ch#43]
Will there be a testflight build too?
The other one was removed because it was outdated.

**Comment by blueforce** [comment]
the ch.admin.bag.dp3t.debug are not available
where can I find the correct test identifier?

**Comment by thebluepotato** [comment]
Since the provisioning profile is limited to one entity per country, I don’t think the provisioning profile will be made available by the FOPH. I guess the only way is to wait for the TestFlight builds, which should be available as soon as testing begins on May 13.

**Comment by blueforce** [comment]
Now I found a worarround for me...
Make a new Buildidentifier e.g. ch.myCompany.myApp and make a Xcode Managed Profile and it works!

**Comment by thebluepotato** [comment]
I would expect Xcode to error out as soon as you try to install on a physical iPhone since it will refuse to codesign the entitlement required for Exposure Notifications.
NB: this is true only for the `feature/exposurenotification-entitlement` branch. You can build and install from the `develop` branch for now, but as soon as it has been merged you’ll need the specific entitlement to build for iOS 13.5.

**Comment by maerki** [comment]
We'll add this to the Readme before we merge to `develop`, but it's true, if you want to test the Exposure Notification framework on a real device, you will need access to an official government account that has the Entitlement for that. We won't be able to provide this for you.

**Comment by maerki** [comment]
@vistalba We currently don't have a TestFlight build, if you need to test the app, you'll have to build it yourself.

**Comment by thebluepotato** [comment]
> @vistalba We currently don't have a TestFlight build, if you need to test the app, you'll have to build it yourself.

However, how will the beta be distributed starting on Wednesday May 13? Will it be through TestFlight? Do you already know approximately how many testers will be involved?

**Comment by christiano-git** [comment]
Is there a way to join the Beta test group ?

Thanks

**Comment by davidperrenoud** [comment]
It seems that the pilot phase has started on May 25th, but only for ETHZ employees and some other public services:
https://ethz.ch/en/news-and-events/eth-news/news/2020/05/swiss-covid-app.html
https://ethz.ch/services/en/news-and-events/solidarity/pilot-swiss-covid-app.html

**Comment by JamesBackInBlack** [comment]
I got access from some link on twitter. Link was https://www.ubique.ch/ something. 
I think the Testflight is open now and you do not need to work for ETHZ.

**Comment by ast3150** [comment]
Found it, https://www.ubique.ch/swisscovid-pilot-ios/

**Comment by davidperrenoud** [comment]
Contrary to what @JamesBackInBlack wrote, please note that this pilot version is **not** intended for the general public and you are breaching the conditions of use:

> 2.1      During the pilot test, the population of possible users will consist solely of members of the Swiss Armed Forces in training or on support or active duty; employees of higher education institutions, hospitals, clinics, cantonal administrations and the Federal Administration; and members of associations wishing to help improve the quality of the system.

Source: [Data Protection Statement & Conditions of Use](https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/situation-schweiz-und-international/datenschutzerklaerung-nutzungsbedingungen.html)

**Comment by JamesBackInBlack** [comment]
Testflight is full now. 

@davidperrenoud Redeem codes or a warning on https://www.ubique.ch/swisscovid-pilot-ios/ could have prevented that.

**Comment by davidperrenoud** [comment]
You cannot make thousands of redeem codes easily if you create a _Public Link_ on Apple TestFlight. I imagine the only workaround would be using fake e-mails like `swisscovid+00001@gmail.com`.

But they could have made at least different groups with a specific _Tester Count_ for each group in order to control leaks. I guess that is too late now.

(I'm not affiliated with Ubique.)
