### ISSUE TITLE
Vorhersagbarkeit, Telefonanruf (AX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-app-ios-ch#49]
Severity: 0 (Blocker)

Screen: Code eingeben - Benötigen Sie Hilfe?

Details:
(1)
(SR-)Benutzer erhalten keine Information, dass bei Klick auf den Button ein Telefonanruf ausgelöst wird.

Allgemein:
Personen welche nicht Telefonieren können (Hörbehinderte, Gehörlose, etc.) haben keine Möglichkeit, die Hilfe zu nutzen / die Hotline zu erreichen

![hilfe](https://user-images.githubusercontent.com/65170302/81574298-e939fd00-93a5-11ea-93f8-6c9b3df4935c.PNG)

**Comment by bastianmorath** [comment]
Screen existiert nicht mehr.
