### ISSUE TITLE
Eingabeblock verdeckt Button  bei kleineren Mobilephones (AX, UX)

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-app-ios-ch#50]
Severity: 0 (Blocker)

Screen: Code eingeben

Details:
Der send Button verschwindet fast ganz auf kleineren Screens.

(das pop up / overlay ist nicht ganz am oberen Rand platziert, da ein back button existiert könnte es um platz zu gewinnen auch den ganzen Bildschirm abdecken)

![covidapp screen size](https://user-images.githubusercontent.com/65170302/81574510-31f1b600-93a6-11ea-8588-e0630abd7bd3.png)

**Comment by maerki** [comment]
`vc.modalPresentationStyle = .fullScreen` bei "kleinen" Phones (iPhone 5 Formfaktor)
