### ISSUE TITLE
Hotline noch nicht aktiv

### ISSUE THREAD

**Issue by Tamara240** [DP-3T/dp3t-app-ios-ch#51]
Severity: 0 (Blocker)

Screen: Code eingeben

Details:
Nicht vergessen die Hotline Nummer als Start zum Telefonanruf zu aktivieren.

![covidapp code hotline](https://user-images.githubusercontent.com/65170302/81574780-885ef480-93a6-11ea-8490-1b41f41def50.png)

**Comment by maerki** [comment]
Die Hotline sollte jetzt aktiv sein.
