### ISSUE TITLE
Stats/charts of encounters over time?

### ISSUE THREAD

**Issue by roman-captural** [DP-3T/dp3t-app-ios-ch#59]
Is there any reason not to display stats/charts in the app about encounters over time to encourage social distancing?

Keeping stats on encounters should be straight forward to implement and might help people to get a feeling for how well they are distancing themselves from others. One could even gamify it like fitness apps that count steps or calories against goals people set for themselves.

I’m not familiar in detail with the technology used for the tracing apps and the state of this project, and therefore might overlook a lot of issues here, but I’m curious to learn if this would be a useful feature or if it is even planned already.

**Comment by maerki** [comment]
Would you mind to move this issue to https://github.com/DP-3T/dp3t-ux-screenflows-ch/issues, then I will answer there

**Comment by roman-captural** [comment]
@maerki I opened the another issue here https://github.com/DP-3T/dp3t-ux-screenflows-ch/issues/3. Moving issues seems only possible with write permissions on both repos. Closing this one.
