### ISSUE TITLE
Covid-19 Benachrichtigung ist deaktviert

### ISSUE THREAD

**Issue by JamesBackInBlack** [DP-3T/dp3t-app-ios-ch#69]
App zeigt Fehler siehe Screenshot.

![IMG_0525](https://user-images.githubusercontent.com/62563961/82923794-bd10a580-9f7b-11ea-8830-1a03b6d97b78.PNG)

Vielleicht ist es ein wenig unglücklich formuliert oder aber ein Bug.
Habe mal beide Varianten aufgeschrieben.

A: Ist ist unglücklich formuliert, verständlicher wäre: "**COVID-19-Kontaktprotokoll deaktiviert** Aktivieren Sie die  Funktion COVID-19_Kontaktprotokoll unter Einstellungen -> Datenschutz -> Health -> COVID-19-Kontaktprotokoll, damit das anonyme Tracing funktioniert.

B: Die Fehlermeldung meint tatsächlich "Benachrichtigungen" im Sinn von "Mitteilungen" und erkennt fälschlicherweise nicht, dass diese aktiv sind.

Klicke ich auf "Akivieren" werde ich umgeleitet auf die App Einstellungen von SwissCovid App. Dort kann aber nur Siri, Mitteilungen und Hintergrundaktual. eingestellt werden. Ich würde direkt nach Datenschutz -> Health verlinken. Sollte dies nicht gehen, würde ich die Verlinkung komplett sein lassen und nur per Text erklären wie es geht.

Verlinkung zu App Settings:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/62563961/82925380-ecc0ad00-9f7d-11ea-8cb8-e302b1e6488d.gif)

Mitteilungen sind aktiv:
![IMG_0526](https://user-images.githubusercontent.com/62563961/82924652-ec73e200-9f7c-11ea-9b50-84610fd28605.PNG)

**Comment by ast3150** [comment]
![Screenshot](https://user-images.githubusercontent.com/3421529/82941598-ea1e8180-9f96-11ea-8a56-a47179f831cf.jpeg) Just received this, most likely related to this issue? Tracing worked previously. Seems like the special permission for the exposure API was removed serverside.

**Comment by JamesBackInBlack** [comment]
![E1386253-6FDF-4C70-9013-0C12AF4F59F7](https://user-images.githubusercontent.com/62563961/82947726-c2341b80-9fa0-11ea-8e0b-217fd6f705fc.png)

Same here, but I think this is Apple fault?

**Comment by ast3150** [comment]
Turning flight mode on and off fixed the issue for me.

**Comment by JamesBackInBlack** [comment]
> Turning flight mode on and off fixed the issue for me.

No luck here. Even reboot did not help.

**Comment by ast3150** [comment]
Are you using a swiss mobile provider? If not, switching to one was recommended to me as a potential solution.

**Comment by JamesBackInBlack** [comment]
> 
> 
> Are you using a swiss mobile provider? If not, switching to one was recommended to me as a potential solution.

I am using a Swisscom eSim and a real Sunrise Sim. Apple ID is also Swiss.

**Comment by JamesBackInBlack** [comment]
Now it works.
It asks for permission and if you redeem the permission, clicking on the "Aktivieren" button redirects to the right settings.
